
mysql:
  host: '192.168.99.108'
  port: 3306
  user: 'root'
  password: 'root'
  database: 'stock_info'



mongo:
  host: '192.168.99.108'
  port: 27017
  db_name: 'stock_db'



redis:
  host: '192.168.99.108'
  port: 6379
  db: 0
  password: ''

td_engine:
  host: '192.168.99.108'
  port: 6030
  user: 'root'
  password: '11111'
  database: 'stock_tick_info'
  timeout: 30



ip_proxy:
    key: ''
    pwd: ''


milvus:
  ip: '192.168.99.108'
  port: 19530
  bge_m3_model_path: 'H:/large_data/modelscope_model/bge_m3'

es:
  host: 'http://192.168.99.108:9200'
  u_name: 'buz_ac'
  u_pwd: '123456'